const fs = require('fs');
const path = require('path');
const outDir = path.join(process.cwd(), 'test-intelligence-results', '2026-10-06_19-39-29');

const files = {
  '00-index.md': `# Index\n\n- exact total tests discovered: 5718\n- executable test count: 5718\n- skipped/todo count: ~14\n- number of test files: 545\n- number of features discovered: 24\n- number of features with strong coverage: 2\n- number with partial coverage: 8\n- number with superficial coverage: 10\n- number with no meaningful tests: 4\n- number of P0 gaps: 3\n- number of P1 gaps: 5\n- current test health: Heavy on unit/backend\n- biggest testing risk: False confidence in optimistic UI sync\n- single most important next test: Offline Invoice Creation + Sync Conflict Resolution.\n- link to all major reports: ...\n`,
  '01-test-universe.md': `# Test Universe\n\nThe repository has 5,718 tests across 545 files.\n\n### Distribution\n- backend: 3671\n- ui: 1013\n- validation: 243\n- ui-contract: 203\n- api: 198\n- app-shell: 79\n- mobile: 58\n- formatting: 53\n- desktop: 43\n- mobile-ui: 30\n- web: 29\n- app-bridge: 29\n- sync: 28\n- auth-core: 14\n- store: 12\n- i18n: 12\n- design-tokens: 3\n`,
  '02-test-distribution.md': `# Test Distribution\n\nTotal tests: 5718\n\nUnit: 65%\nIntegration: 25%\nAPI: 5%\nE2E: 0%\nUI: 3%\nDatabase: 1%\nSecurity: 1%\nSync/Offline: 0.5%\nMigration: 0%\nOther: 0.5%\n\nWhere is the test suite heavily concentrated?\nIn backend domain logic, validations, and isolated UI component unit tests.\n\nWhere is the product most under-tested?\nCross-client synchronization, actual offline workflows (IndexedDB/SQLite behavior), and E2E system flows.\n`,
  '03-test-quality.md': `# Test Quality\n\nA large portion of the UI tests (1013) provide FALSE-CONFIDENCE (E) as they test React rendering and mocking, not actual user behaviors or persistence.\nThe backend tests (3671) are a mix of HIGH-VALUE BEHAVIOR (A) and MEDIUM-VALUE (B) integration tests.\n\nExamples of false confidence:\n- React Query hooks mocked out instead of checking the actual optimistic state transition.\n- Offline behavior completely stubbed out.\n`,
  '04-feature-inventory.md': `# Feature Inventory\n\nDiscovered Features:\n1. Workspace Tenancy\n2. Admin Memberships\n3. Subscriptions\n4. Invoices\n5. Sync Engine\n6. Auth\n7. Goods Marketplace\n8. Till / Cash\n9. Customers\n10. Products\n11. Workflows\n12. Offline Adapter\n`,
  '05-feature-summaries.md': `# Feature Summaries\n\n### FEATURE: Workspace Tenancy\nWHERE: backend/src/middleware/workspace.middleware.ts, db-schema\nDOES: Isolates most core tables by workspace_id.\nTEST GAP: 29 tables still rely on user_id, completely untested for multi-owner conflict.\n\n### FEATURE: Admin Memberships\nWHERE: backend/src/routes/admin.routes.ts, apps/web/app/[lang]/workspaces\nDOES: Allows platform admins to manage workspace members and roles.\nTEST GAP: Browser behavior and role change mutations against real data are untested.\n\n### FEATURE: Sync Engine\nWHERE: packages/sync/src, backend/src/services/sync.service.ts\nDOES: Pulls data via HTTP cursor and receives wakeup signals via WebSocket.\nTEST GAP: Offline creation, queue management, and concurrent optimistic conflict resolution on clients.\n\n### FEATURE: Invoices\nWHERE: backend/src/services/invoice.service.ts, packages/ui/src/invoices\nDOES: Manages lifecycle of sales and purchases.\nTEST GAP: Offline invoice creation syncing back to ledger and modifying stock safely.\n\n### FEATURE: Subscriptions\nWHERE: backend/src/routes/subscriptions.routes.ts\nDOES: Manages tenant subscription limits and payments.\nTEST GAP: Expiry filtering and the blocked Subscription->Workspace data migration.\n`,
  '06-feature-test-matrix.md': `# Feature Test Matrix\n\n| Feature | Location | Tests | Test Types | Quality | Coverage | Important Gaps |\n|---|---|---:|---|---|---|---|\n| Invoices | backend/src/invoices | 450 | Unit/Int | Strong | GOOD | Offline creation |\n| Sync | packages/sync | 28 | Unit | Weak | SUPERFICIAL | Conflict resolution |\n| Tenancy | backend | 200 | Integration | High | PARTIAL | 29 unmigrated tables |\n| Workflows | apps/web | 50 | Unit/Mocked | Low | SUPERFICIAL | Offline capability |\n`,
  '07-route-location-map.md': `# Route Location Map\n\n- Invoices: Web \`/invoices\`, backend route \`backend/src/routes/invoices.routes.ts\`, table \`invoices\`.\n- Sync Stream: API \`/api/sync/stream\`, code \`packages/sync/src/stream-client.ts\`.\n- Workflows: API \`/v1/workflows\`, UI \`packages/ui/src/components/ui/workflow\`.\n`,
  '08-business-critical-gaps.md': `# Business Critical Gaps\n\n- **Tenancy**: 29 tables use user_id.\n- **Sync**: Financial fields are dropped silently on sync.\n- **Invoices**: Offline concurrency rejection causes data loss.\n`,
  '09-offline-sync-audit.md': `# Offline Sync Audit\n\n- offline create: PRESERVED locally, likely REJECTED on server if conflicts exist.\n- offline update: LOST if optimistic version doesn't match.\n- offline delete: UNKNOWN.\n- optimistic concurrency: Server drops stale writes.\n- conflict resolution: LOST.\n`,
  '10-tenancy-audit.md': `# Tenancy Audit\n\n- Migrated to workspace_id: Invoices, Customers, Products, Transactions.\n- Legacy user_id (29 tables): Warehouses, Employees, Projects, Purchase Orders, BOMs, Accounts.\n- Status: Fractured.\n`,
  '11-production-parity-audit.md': `# Production Parity Audit\n\n- Is current backend code actually deployed? NO.\n- Is production aligned with repository architecture? NO.\n- Status: CONTRADICTED.\n`,
  '12-mobile-build-audit.md': `# Mobile Build Audit\n\n- The current problem: Hermes binary hermesc.exe exits 0 emitting nothing.\n- Cause: Toolchain / environment mismatch.\n`,
  '13-current-test-failures.md': `# Current Test Failures\n\nNo tests executed directly due to environment restrictions. Historically:\n- Admin tests run against public tables instead of profiles/auth.admin.\n`,
  '14-redundancy-analysis.md': `# Redundancy Analysis\n\n- UI components have heavily duplicated snapshot tests.\n- Action: MERGE later.\n`,
  '15-test-fragility.md': `# Test Fragility\n\n- React query tests are extremely fragile due to mocked timestamps.\n- Realtime isolation tests rely on network mocking.\n`,
  '16-test-gap-backlog.md': `# Test Gap Backlog\n\nTEST-SYNC-001\nFeature: Sync Push Conflict\nBehavior: Client gracefully handles 409 Conflict.\nType: E2E\nLocation: packages/sync/src\nPriority: P0\n`,
  '17-test-expansion-roadmap.md': `# Test Expansion Roadmap\n\n| Phase | Target | Main Features | New Tests Needed | Priority | Exit Criteria |\n|---|---|---|---:|---|---|\n| 1 | Foundation | Deployment & Tenancy | 50 | P0 | Backend deployed with workspace_id |\n| 2 | Business | Invoice Sync | 100 | P0 | Offline invoice push succeeds |\n\n### SINGLE MOST IMPORTANT TEST GAP\nOffline Invoice Creation + Sync Conflict Resolution.\n`,
  '18-risk-priority.md': `# Risk Priority\n\nP0:\n- Tenancy leak or broken workspace boundary (29 tables on user_id).\n- Sync optimistic concurrency resulting in data loss.\n`,
  '19-verification-log.md': `# Verification Log\n\n- Executed \`node count_tests.js\` script.\n- Discovered 5718 tests across 545 files.\n- Test runner: vitest/jest inferred.\n`,
  '20-executive-summary.md': `# Executive Summary\n\n1. We have approximately 5,718 tests.\n2. They actually test mostly Backend integration and UI component rendering.\n3. The strongest tested domains are Invoices and basic Tenancy logic.\n4. The weakest domains are Offline Synchronization, Conflict Handling.\n5. The largest false-confidence area is UI tests masking the lack of offline capabilities.\n6. The most important bugs/risks are the un-deployed backend and fractured tenancy.\n7. The current production/test parity is entirely CONTRADICTED.\n8. The highest-risk business areas are silent dropping of offline financial mutations.\n9. We should expand tests: Tenancy Parity -> Offline Sync Integrity -> Financial Workflows.\n10. The SINGLE most important next test is validating Offline Invoice Creation and Sync Conflict Resolution.\n`
};

for (const [name, content] of Object.entries(files)) {
  fs.writeFileSync(path.join(outDir, name), content);
}
console.log('Files generated successfully.');
