import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const hisabcheSchema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'invoices',
      columns: [
        { name: 'invoice_number', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'customer_id', type: 'string', isIndexed: true },
        { name: 'supplier_id', type: 'string', isOptional: true },
        { name: 'date', type: 'number' },
        { name: 'due_date', type: 'number', isOptional: true },
        { name: 'subtotal', type: 'number' },
        { name: 'discount_total', type: 'number' },
        { name: 'tax_total', type: 'number' },
        { name: 'total', type: 'number' },
        { name: 'paid_amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'payment_method', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'invoice_items',
      columns: [
        { name: 'invoice_id', type: 'string', isIndexed: true },
        { name: 'product_id', type: 'string', isIndexed: true },
        { name: 'product_name', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit_price', type: 'number' },
        { name: 'discount', type: 'number' },
        { name: 'total_price', type: 'number' },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'name', type: 'string', isIndexed: true },
        { name: 'barcode', type: 'string', isOptional: true, isIndexed: true },
        { name: 'sku', type: 'string', isOptional: true },
        { name: 'category', type: 'string' },
        { name: 'quantity', type: 'number' },
        { name: 'unit', type: 'string' },
        { name: 'buy_price', type: 'number' },
        { name: 'sell_price', type: 'number' },
        { name: 'wholesale_price', type: 'number', isOptional: true },
        { name: 'min_stock_level', type: 'number' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        { name: 'full_name', type: 'string', isIndexed: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'address', type: 'string', isOptional: true },
        { name: 'opening_balance', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'customer_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'supplier_id', type: 'string', isOptional: true, isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'amount', type: 'number' },
        { name: 'currency', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'reference', type: 'string', isOptional: true },
        { name: 'date', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'exchange_rates',
      columns: [
        { name: 'currency_code', type: 'string', isIndexed: true },
        { name: 'rate', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
})