-- ============================================================================
-- docs/base-schema-migration.sql
--
-- GENERATED by scripts/generate-base-schema.mjs from a dump of the live
-- database. Do not hand-edit; regenerate.
--
-- ---------------------------------------------------------------------------
-- WHAT THIS IS
--
-- The 55 tables that were created by hand in the Supabase dashboard, before
-- `docs/*.sql` existed. Every migration since ALTERs them and none of them
-- CREATES them — which was invisible until the schema was dropped and the
-- rebuild produced eleven tables out of sixty-five.
--
-- ---------------------------------------------------------------------------
-- ⚠️ WHAT IT DOES NOT CARRY
--
-- The dump recorded names, types and NOT NULL. It did not record foreign keys,
-- unique constraints, check constraints, indexes or defaults, and this file
-- invents none of them — a guessed foreign key pointing the wrong way fails at
-- midnight on a real insert.
--
-- The migrations that run AFTER this one add the constraints, indexes and RLS
-- policies they know about, which is all of the tenancy work. What is lost is
-- whatever was only ever configured in the dashboard.
--
-- ---------------------------------------------------------------------------
-- IT MUST RUN FIRST
--
-- Everything else in the bundle ALTERs these tables.
--
-- SAFE TO RE-RUN.
-- ============================================================================

BEGIN;

-- ─── Enum types ─────────────────────────────────────────────────────────────
--
-- Referenced by columns below. The dump recorded the type NAMES but not their
-- definitions, so without these the rebuild fails at the first column that
-- uses one.
--
-- Values taken from packages/validation/src/schemas/workflow.schema.ts — the
-- place the application defines them.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'workflow_status') THEN
    CREATE TYPE workflow_status AS ENUM ('pending', 'in_progress', 'approved', 'rejected', 'cancelled');
  END IF;
END $$;   -- workflowStatusEnum

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'workflow_action') THEN
    CREATE TYPE workflow_action AS ENUM ('approved', 'rejected', 'forwarded', 'cancelled');
  END IF;
END $$;   -- workflowActionEnum


-- accounts — held 8 rows before the reset
CREATE TABLE IF NOT EXISTS accounts (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  code                         text NOT NULL,
  name                         text NOT NULL,
  type                         text NOT NULL,
  is_active                    boolean DEFAULT true,
  created_at                   timestamp with time zone DEFAULT now(),
  user_id                      uuid NOT NULL,
  parent_id                    uuid,
  deleted_at                   timestamp without time zone DEFAULT now()
);

-- activities — held 24 rows before the reset
CREATE TABLE IF NOT EXISTS activities (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workspace_id                 uuid NOT NULL,
  actor_id                     uuid,
  entity_type                  text NOT NULL,
  entity_id                    uuid NOT NULL,
  action                       text NOT NULL,
  title                        text NOT NULL,
  description                  text,
  reference_number             text,
  icon                         text,
  metadata                     jsonb DEFAULT '{}'::jsonb NOT NULL,
  entity_snapshot              jsonb DEFAULT '[]'::jsonb,
  importance                   smallint DEFAULT 0 NOT NULL,
  is_read                      boolean DEFAULT false NOT NULL,
  is_pinned                    boolean DEFAULT false NOT NULL,
  is_archived                  boolean DEFAULT false NOT NULL,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at                   timestamp with time zone DEFAULT now() NOT NULL,
  actor_name                   text
);

-- attendance
CREATE TABLE IF NOT EXISTS attendance (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id                  uuid NOT NULL,
  date                         date NOT NULL,
  check_in                     time without time zone,
  check_out                    time without time zone,
  status                       text,
  notes                        text,
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- audit_logs — held 235 rows before the reset
CREATE TABLE IF NOT EXISTS audit_logs (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id                      uuid NOT NULL,
  action                       text NOT NULL,
  entity_type                  text NOT NULL,
  entity_id                    uuid,
  old_data                     jsonb DEFAULT '{}'::jsonb,
  new_data                     jsonb DEFAULT '{}'::jsonb,
  ip_address                   text,
  created_at                   timestamp with time zone DEFAULT now(),
  user_agent                   text
);

-- background_jobs — held 2 rows before the reset
CREATE TABLE IF NOT EXISTS background_jobs (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  job_type                     text NOT NULL,
  status                       text NOT NULL,
  payload                      jsonb DEFAULT '{}'::jsonb,
  scheduled_at                 timestamp with time zone DEFAULT now() NOT NULL,
  started_at                   timestamp with time zone DEFAULT now(),
  completed_at                 timestamp with time zone DEFAULT now(),
  last_error                   text,
  retry_count                  integer DEFAULT 0,
  max_retries                  integer DEFAULT 0,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL
);

-- billing_plans
CREATE TABLE IF NOT EXISTS billing_plans (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  key                          text NOT NULL,
  name                         text NOT NULL,
  description                  text,
  price_monthly                integer DEFAULT 0,
  price_yearly                 integer DEFAULT 0,
  is_active                    boolean DEFAULT true,
  features                     jsonb DEFAULT '[]'::jsonb NOT NULL,
  limits                       jsonb DEFAULT '{}'::jsonb NOT NULL,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now()
);

-- bom_items
CREATE TABLE IF NOT EXISTS bom_items (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  bom_id                       uuid,
  raw_material_id              uuid,
  quantity                     numeric DEFAULT 0 NOT NULL,
  unit_cost                    numeric DEFAULT 0,
  user_id                      uuid
);

-- boms
CREATE TABLE IF NOT EXISTS boms (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id                   uuid,
  version                      integer DEFAULT 0,
  is_active                    boolean DEFAULT true,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- checkout_sessions
CREATE TABLE IF NOT EXISTS checkout_sessions (
  id                           text NOT NULL,
  user_id                      uuid NOT NULL,
  plan                         text NOT NULL,
  interval                     text NOT NULL,
  status                       text NOT NULL,
  stripe_session_id            text,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now(),
  workspace_id                 uuid NOT NULL
);

-- customers — held 26 rows before the reset
CREATE TABLE IF NOT EXISTS customers (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  full_name                    text NOT NULL,
  phone                        text,
  email                        text,
  address                      text,
  opening_balance              numeric(12,2) DEFAULT 0,
  is_active                    boolean DEFAULT true,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now(),
  synced_at                    timestamp with time zone DEFAULT now(),
  user_id                      uuid,
  notes                        text,
  type                         text,
  search_vector                tsvector,
  version                      bigint DEFAULT 0 NOT NULL,
  workspace_id                 uuid
);

-- departments — held 2 rows before the reset
CREATE TABLE IF NOT EXISTS departments (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  name_en                      text,
  parent_id                    uuid,
  manager_id                   uuid,
  description                  text,
  is_active                    boolean DEFAULT true,
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- employees — held 7 rows before the reset
CREATE TABLE IF NOT EXISTS employees (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_code                text NOT NULL,
  first_name                   text NOT NULL,
  last_name                    text NOT NULL,
  father_name                  text,
  national_id                  text,
  passport_number              text,
  date_of_birth                date,
  gender                       text,
  marital_status               text,
  email                        text,
  phone                        text,
  emergency_contact            text,
  address                      text,
  city                         text,
  province                     text,
  photo_url                    text,
  department_id                uuid,
  position                     text,
  employment_type              text,
  hire_date                    date NOT NULL,
  termination_date             date,
  status                       text,
  salary                       numeric DEFAULT 0,
  salary_currency              text,
  bank_account                 text,
  bank_name                    text,
  user_id                      uuid,
  notes                        text,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- event_log — held 65 rows before the reset
CREATE TABLE IF NOT EXISTS event_log (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_type                   text NOT NULL,
  entity_type                  text NOT NULL,
  entity_id                    uuid NOT NULL,
  payload                      jsonb DEFAULT '{}'::jsonb,
  processed                    boolean DEFAULT true,
  created_at                   timestamp with time zone DEFAULT now(),
  user_id                      uuid NOT NULL,
  retry_count                  integer DEFAULT 0,
  max_retries                  integer DEFAULT 0,
  next_retry_at                timestamp with time zone DEFAULT now(),
  error_message                text,
  completed_at                 timestamp with time zone DEFAULT now(),
  idempotency_key              text,
  sequence_number              bigint DEFAULT 0 NOT NULL,
  tenant_id                    uuid,
  realtime_sent                boolean DEFAULT true,
  sync_sent                    boolean DEFAULT true,
  webhook_sent                 boolean DEFAULT true,
  correlation_id               uuid
);

-- event_types — held 25 rows before the reset
CREATE TABLE IF NOT EXISTS event_types (
  type                         text NOT NULL,
  description                  text,
  schema_version               integer DEFAULT 0
);

-- interactions — held 4 rows before the reset
CREATE TABLE IF NOT EXISTS interactions (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id                  uuid,
  type                         text,
  subject                      text,
  content                      text,
  interaction_date             timestamp without time zone,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  status                       text NOT NULL,
  public_token                 uuid DEFAULT gen_random_uuid() NOT NULL,
  employee_id                  uuid,
  employee_name                text,
  customers_snapshot           jsonb DEFAULT '[]'::jsonb NOT NULL,
  status_history               jsonb DEFAULT '[]'::jsonb NOT NULL,
  customer_outcomes            jsonb DEFAULT '[]'::jsonb NOT NULL
);

-- invoice_items — held 85 rows before the reset
CREATE TABLE IF NOT EXISTS invoice_items (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_id                   uuid NOT NULL,
  product_id                   uuid,
  product_name                 text,
  quantity                     numeric(12,3) DEFAULT 0,
  unit_price                   numeric(12,2) DEFAULT 0,
  discount                     numeric(5,2) DEFAULT 0,
  total_price                  numeric(12,2) DEFAULT 0,
  created_at                   timestamp with time zone DEFAULT now(),
  user_id                      uuid,
  notes                        text,
  unit                         text NOT NULL,
  weight_grams                 numeric(12,3) DEFAULT 0,
  unit_label                   text
);

-- invoice_pdf_cache
CREATE TABLE IF NOT EXISTS invoice_pdf_cache (
  invoice_id                   uuid NOT NULL,
  storage_path                 text NOT NULL,
  version_key                  text NOT NULL,
  generated_at                 timestamp with time zone DEFAULT now() NOT NULL
);

-- invoices — held 80 rows before the reset
CREATE TABLE IF NOT EXISTS invoices (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  invoice_number               text NOT NULL,
  type                         text NOT NULL,
  customer_id                  uuid,
  supplier_id                  uuid,
  date                         timestamp with time zone NOT NULL,
  due_date                     timestamp with time zone,
  subtotal                     numeric(12,2) DEFAULT 0,
  discount_total               numeric(12,2) DEFAULT 0,
  tax_total                    numeric(12,2) DEFAULT 0,
  total                        numeric(12,2) DEFAULT 0 NOT NULL,
  paid_amount                  numeric(12,2) DEFAULT 0,
  currency                     text,
  payment_method               text,
  status                       text,
  notes                        text,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now(),
  synced_at                    timestamp with time zone DEFAULT now(),
  user_id                      uuid,
  discount_type                text,
  reference                    text,
  tax_rate                     numeric DEFAULT 0,
  search_vector                tsvector,
  purchase_order_id            uuid,
  public_token                 uuid DEFAULT gen_random_uuid() NOT NULL,
  version                      bigint DEFAULT 0 NOT NULL,
  locked_by_user_id            uuid,
  lock_expires_at              timestamp with time zone DEFAULT now(),
  finalized_at                 timestamp with time zone DEFAULT now(),
  workspace_id                 uuid
);

-- journal_entries — held 10 rows before the reset
CREATE TABLE IF NOT EXISTS journal_entries (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  date                         date NOT NULL,
  description                  text,
  reference                    text,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now(),
  deleted_at                   timestamp without time zone DEFAULT now()
);

-- journal_lines — held 40 rows before the reset
CREATE TABLE IF NOT EXISTS journal_lines (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  journal_id                   uuid,
  account_id                   uuid,
  debit                        numeric(19,4) DEFAULT 0 NOT NULL,
  credit                       numeric(19,4) DEFAULT 0 NOT NULL,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now()
);

-- leaves
CREATE TABLE IF NOT EXISTS leaves (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id                  uuid NOT NULL,
  leave_type                   text NOT NULL,
  start_date                   date NOT NULL,
  end_date                     date NOT NULL,
  total_days                   integer DEFAULT 0 NOT NULL,
  reason                       text,
  status                       text,
  approved_by                  uuid,
  approved_at                  timestamp without time zone DEFAULT now(),
  notes                        text,
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- ledger_entries — held 218 rows before the reset
CREATE TABLE IF NOT EXISTS ledger_entries (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  account_id                   uuid NOT NULL,
  debit                        numeric DEFAULT 0,
  credit                       numeric DEFAULT 0,
  reference_type               text NOT NULL,
  reference_id                 uuid NOT NULL,
  description                  text,
  entry_date                   timestamp with time zone,
  created_at                   timestamp with time zone DEFAULT now(),
  user_id                      uuid NOT NULL
);

-- notifications — held 154 rows before the reset
CREATE TABLE IF NOT EXISTS notifications (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workspace_id                 uuid NOT NULL,
  user_id                      uuid NOT NULL,
  title                        text NOT NULL,
  body                         text,
  type                         text NOT NULL,
  action_url                   text,
  entity_type                  text,
  entity_id                    uuid,
  is_read                      boolean DEFAULT false NOT NULL,
  metadata                     jsonb DEFAULT '{}'::jsonb,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL,
  workflow_instance_id         uuid,
  read_at                      timestamp with time zone DEFAULT now()
);

-- opportunities
CREATE TABLE IF NOT EXISTS opportunities (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id                  uuid,
  title                        text NOT NULL,
  description                  text,
  stage                        text,
  value                        numeric(19,4) DEFAULT 0,
  expected_close_date          date,
  probability                  integer DEFAULT 0,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- password_reset_tokens — held 8 rows before the reset
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workspace_id                 uuid,
  user_id                      uuid NOT NULL,
  token_hash                   text NOT NULL,
  expires_at                   timestamp with time zone DEFAULT now() NOT NULL,
  used_at                      timestamp with time zone DEFAULT now(),
  revoked_at                   timestamp with time zone DEFAULT now(),
  requested_ip                 inet,
  requested_user_agent         text,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now(),
  deleted_at                   timestamp with time zone DEFAULT now()
);

-- payrolls — held 4 rows before the reset
CREATE TABLE IF NOT EXISTS payrolls (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  employee_id                  uuid NOT NULL,
  period_start                 date NOT NULL,
  period_end                   date NOT NULL,
  base_salary                  numeric DEFAULT 0 NOT NULL,
  bonuses                      numeric DEFAULT 0,
  deductions                   numeric DEFAULT 0,
  overtime_hours               numeric DEFAULT 0,
  overtime_rate                numeric DEFAULT 0,
  overtime_amount              numeric DEFAULT 0,
  tax_amount                   numeric DEFAULT 0,
  net_salary                   numeric DEFAULT 0 NOT NULL,
  currency                     text,
  status                       text,
  payment_date                 timestamp without time zone,
  notes                        text,
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- permissions — held 33 rows before the reset
CREATE TABLE IF NOT EXISTS permissions (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  code                         text NOT NULL,
  name                         text NOT NULL,
  description                  text,
  resource                     text NOT NULL,
  action                       text NOT NULL,
  created_at                   timestamp without time zone DEFAULT now()
);

-- products — held 26 rows before the reset
CREATE TABLE IF NOT EXISTS products (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  barcode                      text,
  sku                          text,
  category                     text,
  quantity                     integer DEFAULT 0,
  unit                         text,
  buy_price                    numeric DEFAULT 0,
  sell_price                   numeric DEFAULT 0,
  wholesale_price              numeric DEFAULT 0,
  min_stock_level              integer DEFAULT 0,
  description                  text,
  is_active                    boolean DEFAULT true,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now(),
  synced_at                    timestamp without time zone DEFAULT now(),
  user_id                      uuid,
  image_url                    text,
  search_vector                tsvector,
  version                      bigint DEFAULT 0 NOT NULL,
  workspace_id                 uuid
);

-- profiles — held 6 rows before the reset
CREATE TABLE IF NOT EXISTS profiles (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  full_name                    text NOT NULL,
  business_name                text,
  avatar_url                   text,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now(),
  preferred_language           text,
  onboarding_completed_at      timestamp with time zone DEFAULT now(),
  business_types               text[] NOT NULL,
  store_size                   text,
  business_note                text
);

-- project_members — held 3 rows before the reset
CREATE TABLE IF NOT EXISTS project_members (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id                   uuid NOT NULL,
  employee_id                  uuid,
  user_id                      uuid,
  role                         text,
  user_id_owner                uuid NOT NULL,
  joined_at                    timestamp without time zone DEFAULT now(),
  created_at                   timestamp without time zone DEFAULT now()
);

-- project_tasks — held 5 rows before the reset
CREATE TABLE IF NOT EXISTS project_tasks (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id                   uuid NOT NULL,
  title                        text NOT NULL,
  description                  text,
  assignee_id                  uuid,
  parent_task_id               uuid,
  status                       text,
  priority                     text,
  estimated_hours              numeric DEFAULT 0,
  actual_hours                 numeric DEFAULT 0,
  due_date                     date,
  completed_at                 timestamp without time zone DEFAULT now(),
  order_index                  integer DEFAULT 0,
  tags                         text[],
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- project_time_entries
CREATE TABLE IF NOT EXISTS project_time_entries (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  project_id                   uuid NOT NULL,
  task_id                      uuid,
  employee_id                  uuid NOT NULL,
  date                         date NOT NULL,
  hours                        numeric DEFAULT 0 NOT NULL,
  description                  text,
  billable                     boolean DEFAULT true,
  hourly_rate                  numeric DEFAULT 0,
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- projects — held 5 rows before the reset
CREATE TABLE IF NOT EXISTS projects (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  description                  text,
  client_id                    uuid,
  start_date                   date,
  end_date                     date,
  budget                       numeric DEFAULT 0,
  currency                     text,
  status                       text,
  priority                     text,
  progress                     integer DEFAULT 0,
  tags                         text[],
  user_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- purchase_order_items
CREATE TABLE IF NOT EXISTS purchase_order_items (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  purchase_order_id            uuid,
  product_id                   uuid,
  quantity                     numeric DEFAULT 0 NOT NULL,
  unit_price                   numeric DEFAULT 0 NOT NULL,
  total_price                  numeric DEFAULT 0 NOT NULL,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now()
);

-- purchase_orders
CREATE TABLE IF NOT EXISTS purchase_orders (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  supplier_id                  uuid,
  order_date                   timestamp without time zone,
  expected_delivery_date       timestamp without time zone,
  status                       text,
  notes                        text,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now(),
  received_at                  timestamp without time zone DEFAULT now(),
  invoice_id                   uuid
);

-- role_permissions — held 128 rows before the reset
CREATE TABLE IF NOT EXISTS role_permissions (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  role_id                      uuid NOT NULL,
  permission_id                uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now()
);

-- roles — held 9 rows before the reset
CREATE TABLE IF NOT EXISTS roles (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  description                  text,
  is_system                    boolean DEFAULT false,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- stock_movements — held 65 rows before the reset
CREATE TABLE IF NOT EXISTS stock_movements (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id                   uuid NOT NULL,
  type                         text NOT NULL,
  quantity                     numeric DEFAULT 0 NOT NULL,
  reference_type               text,
  reference_id                 uuid,
  notes                        text,
  created_at                   timestamp with time zone DEFAULT now(),
  user_id                      uuid NOT NULL,
  from_warehouse_id            uuid,
  to_warehouse_id              uuid
);

-- subscriptions — held 1 rows before the reset
CREATE TABLE IF NOT EXISTS subscriptions (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id                      uuid NOT NULL,
  plan                         text NOT NULL,
  status                       text NOT NULL,
  trial_started_at             timestamp with time zone DEFAULT now() NOT NULL,
  trial_ends_at                timestamp with time zone DEFAULT now() NOT NULL,
  period_start                 timestamp with time zone NOT NULL,
  period_end                   timestamp with time zone NOT NULL,
  cancel_at_period_end         boolean DEFAULT true,
  stripe_customer_id           text,
  stripe_subscription_id       text,
  created_at                   timestamp with time zone DEFAULT now(),
  updated_at                   timestamp with time zone DEFAULT now(),
  is_trial                     boolean DEFAULT true,
  trial_used                   boolean DEFAULT true,
  workspace_id                 uuid NOT NULL
);

-- suppliers
CREATE TABLE IF NOT EXISTS suppliers (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  phone                        text,
  email                        text,
  address                      jsonb DEFAULT '{}'::jsonb,
  user_id                      uuid,
  is_active                    boolean DEFAULT true,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- sync_logs
CREATE TABLE IF NOT EXISTS sync_logs (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id                      uuid NOT NULL,
  started_at                   timestamp without time zone DEFAULT now() NOT NULL,
  completed_at                 timestamp without time zone DEFAULT now(),
  status                       text,
  items_processed              integer DEFAULT 0,
  items_failed                 integer DEFAULT 0,
  items_total                  integer DEFAULT 0,
  error_message                text,
  created_at                   timestamp without time zone DEFAULT now()
);

-- sync_queue
CREATE TABLE IF NOT EXISTS sync_queue (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id                      uuid NOT NULL,
  entity_type                  text NOT NULL,
  entity_id                    uuid,
  action                       text NOT NULL,
  payload                      jsonb DEFAULT '{}'::jsonb NOT NULL,
  status                       text,
  priority                     integer DEFAULT 0,
  retry_count                  integer DEFAULT 0,
  max_retries                  integer DEFAULT 0,
  error_message                text,
  created_at                   timestamp without time zone DEFAULT now(),
  processed_at                 timestamp without time zone DEFAULT now()
);

-- transactions — held 22 rows before the reset
CREATE TABLE IF NOT EXISTS transactions (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_id                  uuid,
  supplier_id                  uuid,
  type                         text NOT NULL,
  amount                       numeric(12,2) DEFAULT 0 NOT NULL,
  currency                     text,
  description                  text,
  reference                    text,
  date                         timestamp with time zone,
  created_at                   timestamp with time zone DEFAULT now(),
  synced_at                    timestamp with time zone DEFAULT now(),
  user_id                      uuid,
  invoice_id                   uuid,
  workspace_id                 uuid
);

-- user_roles — held 2 rows before the reset
CREATE TABLE IF NOT EXISTS user_roles (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id                      uuid NOT NULL,
  role_id                      uuid NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  workspace_id                 uuid
);

-- warehouse_stock
CREATE TABLE IF NOT EXISTS warehouse_stock (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  warehouse_id                 uuid NOT NULL,
  product_id                   uuid NOT NULL,
  quantity                     numeric DEFAULT 0 NOT NULL,
  user_id                      uuid NOT NULL,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at                   timestamp with time zone DEFAULT now() NOT NULL
);

-- warehouses
CREATE TABLE IF NOT EXISTS warehouses (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  location                     text,
  is_active                    boolean DEFAULT true,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now(),
  deleted_at                   timestamp without time zone DEFAULT now()
);

-- webhook_events
CREATE TABLE IF NOT EXISTS webhook_events (
  id                           text NOT NULL,
  type                         text NOT NULL,
  payload                      jsonb DEFAULT '{}'::jsonb NOT NULL,
  processed_at                 timestamp with time zone DEFAULT now()
);

-- work_orders
CREATE TABLE IF NOT EXISTS work_orders (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id                   uuid,
  quantity                     integer DEFAULT 0 NOT NULL,
  bom_id                       uuid,
  status                       text,
  start_date                   timestamp without time zone,
  end_date                     timestamp without time zone,
  user_id                      uuid,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now()
);

-- workflow_actions — held 44 rows before the reset
CREATE TABLE IF NOT EXISTS workflow_actions (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  instance_id                  uuid NOT NULL,
  step_order                   integer DEFAULT 0 NOT NULL,
  action                       workflow_action NOT NULL,
  actor_user_id                uuid NOT NULL,
  actor_role                   text,
  comment                      text,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL
);

-- workflow_instances — held 41 rows before the reset
CREATE TABLE IF NOT EXISTS workflow_instances (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workflow_id                  uuid NOT NULL,
  workspace_id                 uuid NOT NULL,
  entity_type                  text NOT NULL,
  entity_id                    uuid NOT NULL,
  status                       workflow_status NOT NULL,
  current_step                 integer DEFAULT 0 NOT NULL,
  total_steps                  integer DEFAULT 0 NOT NULL,
  started_at                   timestamp with time zone DEFAULT now() NOT NULL,
  completed_at                 timestamp with time zone DEFAULT now(),
  created_at                   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at                   timestamp with time zone DEFAULT now() NOT NULL
);

-- workflow_steps — held 2 rows before the reset
CREATE TABLE IF NOT EXISTS workflow_steps (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workflow_id                  uuid NOT NULL,
  step_order                   integer DEFAULT 0 NOT NULL,
  approver_role                text NOT NULL,
  approver_user_id             uuid,
  is_final                     boolean DEFAULT false NOT NULL,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL
);

-- workflows — held 1 rows before the reset
CREATE TABLE IF NOT EXISTS workflows (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workspace_id                 uuid NOT NULL,
  name                         text NOT NULL,
  description                  text,
  entity_type                  text NOT NULL,
  is_active                    boolean DEFAULT true NOT NULL,
  created_at                   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at                   timestamp with time zone DEFAULT now() NOT NULL,
  deleted_at                   timestamp with time zone DEFAULT now()
);

-- workspace_invites — held 23 rows before the reset
CREATE TABLE IF NOT EXISTS workspace_invites (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workspace_id                 uuid NOT NULL,
  email                        text NOT NULL,
  role                         text,
  invited_by                   uuid NOT NULL,
  token                        text,
  status                       text,
  expires_at                   timestamp without time zone DEFAULT now() NOT NULL,
  created_at                   timestamp without time zone DEFAULT now(),
  token_hash                   text,
  accepted_at                  timestamp with time zone DEFAULT now(),
  accepted_by                  uuid
);

-- workspace_members — held 6 rows before the reset
CREATE TABLE IF NOT EXISTS workspace_members (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  workspace_id                 uuid NOT NULL,
  user_id                      uuid NOT NULL,
  role                         text,
  joined_at                    timestamp without time zone DEFAULT now(),
  created_at                   timestamp without time zone DEFAULT now(),
  job_title                    text,
  phone                        text,
  has_access                   boolean DEFAULT true NOT NULL,
  suspended_at                 timestamp with time zone DEFAULT now()
);

-- workspaces — held 6 rows before the reset
CREATE TABLE IF NOT EXISTS workspaces (
  id                           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name                         text NOT NULL,
  slug                         text NOT NULL,
  description                  text,
  logo_url                     text,
  owner_id                     uuid NOT NULL,
  is_active                    boolean DEFAULT true,
  created_at                   timestamp without time zone DEFAULT now(),
  updated_at                   timestamp without time zone DEFAULT now(),
  stamp_url                    text
);


-- ─── Row level security ─────────────────────────────────────────────────────
--
-- Turned on here, with NO policy yet. Between this file and the policy
-- migrations these tables are readable by nobody, which is the safe direction
-- to be wrong in. `tenancy-rls.sql` and the files after it add the policies.

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE background_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE bom_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE boms ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkout_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_pdf_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE journal_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE leaves ENABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE opportunities ENABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE payrolls ENABLE ROW LEVEL SECURITY;
ALTER TABLE permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_time_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE role_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouse_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_instances ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflow_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE workflows ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_invites ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY;


COMMIT;
