-- ============================================================================
-- docs/hardening-migration.sql
--
-- GENERATED by scripts/generate-hardening.mjs. Do not hand-edit.
--
-- The constraints and indexes `base-schema-migration.sql` could not carry,
-- because the dump it was built from recorded only names, types and NOT NULL.
--
-- ---------------------------------------------------------------------------
-- FOREIGN KEYS ARE ADDED `NOT VALID`
--
-- Which means: enforced on every future insert and update, and NOT checked
-- against rows that already exist.
--
-- That is the right trade here. The tables are empty on a fresh rebuild so
-- there is nothing to check; on a database with data, a validating ALTER takes
-- an ACCESS EXCLUSIVE lock for as long as the scan runs — which on a large
-- `invoice_items` is an outage. Validate later, deliberately:
--
--     ALTER TABLE invoice_items VALIDATE CONSTRAINT invoice_items_invoice_id_fkey;
--
-- ⚠️ No `ON DELETE CASCADE` anywhere. Postgres defaults to RESTRICT, and on a
-- financial schema that is what you want: deleting a customer who has invoices
-- should REFUSE, not quietly remove the invoices.
--
-- ---------------------------------------------------------------------------
-- INDEXES ARE CHOSEN, NOT SPRAYED
--
-- Every foreign key gets one — Postgres does not create them, and without one
-- a parent delete scans the whole child table. Beyond that, only composites
-- that match a real ORDER BY or WHERE in the backend.
--
-- Indexing every column costs write throughput, storage and vacuum time. A
-- table with nine indexes is measurably slower to insert into than one with
-- three, and inserts are what a till does all day.
--
-- SAFE TO RE-RUN.
-- ============================================================================

BEGIN;

-- ─── Foreign keys (48) ─────────────────────────────────────────────────────

ALTER TABLE activities DROP CONSTRAINT IF EXISTS activities_workspace_id_fkey;
ALTER TABLE activities ADD CONSTRAINT activities_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE attendance DROP CONSTRAINT IF EXISTS attendance_employee_id_fkey;
ALTER TABLE attendance ADD CONSTRAINT attendance_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees (id) NOT VALID;

ALTER TABLE boms DROP CONSTRAINT IF EXISTS boms_product_id_fkey;
ALTER TABLE boms ADD CONSTRAINT boms_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES products (id) NOT VALID;

ALTER TABLE checkout_sessions DROP CONSTRAINT IF EXISTS checkout_sessions_workspace_id_fkey;
ALTER TABLE checkout_sessions ADD CONSTRAINT checkout_sessions_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE customers DROP CONSTRAINT IF EXISTS customers_workspace_id_fkey;
ALTER TABLE customers ADD CONSTRAINT customers_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE employees DROP CONSTRAINT IF EXISTS employees_department_id_fkey;
ALTER TABLE employees ADD CONSTRAINT employees_department_id_fkey
  FOREIGN KEY (department_id) REFERENCES departments (id) NOT VALID;

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_customer_id_fkey;
ALTER TABLE interactions ADD CONSTRAINT interactions_customer_id_fkey
  FOREIGN KEY (customer_id) REFERENCES customers (id) NOT VALID;

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_employee_id_fkey;
ALTER TABLE interactions ADD CONSTRAINT interactions_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees (id) NOT VALID;

ALTER TABLE invoice_items DROP CONSTRAINT IF EXISTS invoice_items_product_id_fkey;
ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES products (id) NOT VALID;

ALTER TABLE invoice_items DROP CONSTRAINT IF EXISTS invoice_items_invoice_id_fkey;
ALTER TABLE invoice_items ADD CONSTRAINT invoice_items_invoice_id_fkey
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) NOT VALID;

ALTER TABLE invoice_pdf_cache DROP CONSTRAINT IF EXISTS invoice_pdf_cache_invoice_id_fkey;
ALTER TABLE invoice_pdf_cache ADD CONSTRAINT invoice_pdf_cache_invoice_id_fkey
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) NOT VALID;

ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_workspace_id_fkey;
ALTER TABLE invoices ADD CONSTRAINT invoices_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_customer_id_fkey;
ALTER TABLE invoices ADD CONSTRAINT invoices_customer_id_fkey
  FOREIGN KEY (customer_id) REFERENCES customers (id) NOT VALID;

ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_supplier_id_fkey;
ALTER TABLE invoices ADD CONSTRAINT invoices_supplier_id_fkey
  FOREIGN KEY (supplier_id) REFERENCES suppliers (id) NOT VALID;

ALTER TABLE invoices DROP CONSTRAINT IF EXISTS invoices_purchase_order_id_fkey;
ALTER TABLE invoices ADD CONSTRAINT invoices_purchase_order_id_fkey
  FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) NOT VALID;

ALTER TABLE journal_lines DROP CONSTRAINT IF EXISTS journal_lines_account_id_fkey;
ALTER TABLE journal_lines ADD CONSTRAINT journal_lines_account_id_fkey
  FOREIGN KEY (account_id) REFERENCES accounts (id) NOT VALID;

ALTER TABLE leaves DROP CONSTRAINT IF EXISTS leaves_employee_id_fkey;
ALTER TABLE leaves ADD CONSTRAINT leaves_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees (id) NOT VALID;

ALTER TABLE ledger_entries DROP CONSTRAINT IF EXISTS ledger_entries_account_id_fkey;
ALTER TABLE ledger_entries ADD CONSTRAINT ledger_entries_account_id_fkey
  FOREIGN KEY (account_id) REFERENCES accounts (id) NOT VALID;

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_workspace_id_fkey;
ALTER TABLE notifications ADD CONSTRAINT notifications_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE opportunities DROP CONSTRAINT IF EXISTS opportunities_customer_id_fkey;
ALTER TABLE opportunities ADD CONSTRAINT opportunities_customer_id_fkey
  FOREIGN KEY (customer_id) REFERENCES customers (id) NOT VALID;

ALTER TABLE password_reset_tokens DROP CONSTRAINT IF EXISTS password_reset_tokens_workspace_id_fkey;
ALTER TABLE password_reset_tokens ADD CONSTRAINT password_reset_tokens_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE payrolls DROP CONSTRAINT IF EXISTS payrolls_employee_id_fkey;
ALTER TABLE payrolls ADD CONSTRAINT payrolls_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees (id) NOT VALID;

ALTER TABLE products DROP CONSTRAINT IF EXISTS products_workspace_id_fkey;
ALTER TABLE products ADD CONSTRAINT products_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_employee_id_fkey;
ALTER TABLE project_members ADD CONSTRAINT project_members_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees (id) NOT VALID;

ALTER TABLE project_members DROP CONSTRAINT IF EXISTS project_members_project_id_fkey;
ALTER TABLE project_members ADD CONSTRAINT project_members_project_id_fkey
  FOREIGN KEY (project_id) REFERENCES projects (id) NOT VALID;

ALTER TABLE project_tasks DROP CONSTRAINT IF EXISTS project_tasks_project_id_fkey;
ALTER TABLE project_tasks ADD CONSTRAINT project_tasks_project_id_fkey
  FOREIGN KEY (project_id) REFERENCES projects (id) NOT VALID;

ALTER TABLE project_time_entries DROP CONSTRAINT IF EXISTS project_time_entries_employee_id_fkey;
ALTER TABLE project_time_entries ADD CONSTRAINT project_time_entries_employee_id_fkey
  FOREIGN KEY (employee_id) REFERENCES employees (id) NOT VALID;

ALTER TABLE project_time_entries DROP CONSTRAINT IF EXISTS project_time_entries_project_id_fkey;
ALTER TABLE project_time_entries ADD CONSTRAINT project_time_entries_project_id_fkey
  FOREIGN KEY (project_id) REFERENCES projects (id) NOT VALID;

ALTER TABLE purchase_order_items DROP CONSTRAINT IF EXISTS purchase_order_items_product_id_fkey;
ALTER TABLE purchase_order_items ADD CONSTRAINT purchase_order_items_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES products (id) NOT VALID;

ALTER TABLE purchase_order_items DROP CONSTRAINT IF EXISTS purchase_order_items_purchase_order_id_fkey;
ALTER TABLE purchase_order_items ADD CONSTRAINT purchase_order_items_purchase_order_id_fkey
  FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders (id) NOT VALID;

ALTER TABLE purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_invoice_id_fkey;
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_invoice_id_fkey
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) NOT VALID;

ALTER TABLE purchase_orders DROP CONSTRAINT IF EXISTS purchase_orders_supplier_id_fkey;
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_supplier_id_fkey
  FOREIGN KEY (supplier_id) REFERENCES suppliers (id) NOT VALID;

ALTER TABLE stock_movements DROP CONSTRAINT IF EXISTS stock_movements_product_id_fkey;
ALTER TABLE stock_movements ADD CONSTRAINT stock_movements_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES products (id) NOT VALID;

ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS subscriptions_workspace_id_fkey;
ALTER TABLE subscriptions ADD CONSTRAINT subscriptions_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_workspace_id_fkey;
ALTER TABLE transactions ADD CONSTRAINT transactions_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_customer_id_fkey;
ALTER TABLE transactions ADD CONSTRAINT transactions_customer_id_fkey
  FOREIGN KEY (customer_id) REFERENCES customers (id) NOT VALID;

ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_invoice_id_fkey;
ALTER TABLE transactions ADD CONSTRAINT transactions_invoice_id_fkey
  FOREIGN KEY (invoice_id) REFERENCES invoices (id) NOT VALID;

ALTER TABLE transactions DROP CONSTRAINT IF EXISTS transactions_supplier_id_fkey;
ALTER TABLE transactions ADD CONSTRAINT transactions_supplier_id_fkey
  FOREIGN KEY (supplier_id) REFERENCES suppliers (id) NOT VALID;

ALTER TABLE user_roles DROP CONSTRAINT IF EXISTS user_roles_workspace_id_fkey;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE warehouse_stock DROP CONSTRAINT IF EXISTS warehouse_stock_product_id_fkey;
ALTER TABLE warehouse_stock ADD CONSTRAINT warehouse_stock_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES products (id) NOT VALID;

ALTER TABLE warehouse_stock DROP CONSTRAINT IF EXISTS warehouse_stock_warehouse_id_fkey;
ALTER TABLE warehouse_stock ADD CONSTRAINT warehouse_stock_warehouse_id_fkey
  FOREIGN KEY (warehouse_id) REFERENCES warehouses (id) NOT VALID;

ALTER TABLE work_orders DROP CONSTRAINT IF EXISTS work_orders_product_id_fkey;
ALTER TABLE work_orders ADD CONSTRAINT work_orders_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES products (id) NOT VALID;

ALTER TABLE workflow_instances DROP CONSTRAINT IF EXISTS workflow_instances_workspace_id_fkey;
ALTER TABLE workflow_instances ADD CONSTRAINT workflow_instances_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE workflow_instances DROP CONSTRAINT IF EXISTS workflow_instances_workflow_id_fkey;
ALTER TABLE workflow_instances ADD CONSTRAINT workflow_instances_workflow_id_fkey
  FOREIGN KEY (workflow_id) REFERENCES workflows (id) NOT VALID;

ALTER TABLE workflow_steps DROP CONSTRAINT IF EXISTS workflow_steps_workflow_id_fkey;
ALTER TABLE workflow_steps ADD CONSTRAINT workflow_steps_workflow_id_fkey
  FOREIGN KEY (workflow_id) REFERENCES workflows (id) NOT VALID;

ALTER TABLE workflows DROP CONSTRAINT IF EXISTS workflows_workspace_id_fkey;
ALTER TABLE workflows ADD CONSTRAINT workflows_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE workspace_invites DROP CONSTRAINT IF EXISTS workspace_invites_workspace_id_fkey;
ALTER TABLE workspace_invites ADD CONSTRAINT workspace_invites_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

ALTER TABLE workspace_members DROP CONSTRAINT IF EXISTS workspace_members_workspace_id_fkey;
ALTER TABLE workspace_members ADD CONSTRAINT workspace_members_workspace_id_fkey
  FOREIGN KEY (workspace_id) REFERENCES workspaces (id) NOT VALID;

-- ─── Indexes (58) ──────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS activities_workspace_id_idx ON activities (workspace_id);
CREATE INDEX IF NOT EXISTS attendance_employee_id_idx ON attendance (employee_id);
CREATE INDEX IF NOT EXISTS boms_product_id_idx ON boms (product_id);
CREATE INDEX IF NOT EXISTS checkout_sessions_workspace_id_idx ON checkout_sessions (workspace_id);
CREATE INDEX IF NOT EXISTS customers_workspace_id_idx ON customers (workspace_id);
CREATE INDEX IF NOT EXISTS employees_department_id_idx ON employees (department_id);
CREATE INDEX IF NOT EXISTS interactions_customer_id_idx ON interactions (customer_id);
CREATE INDEX IF NOT EXISTS interactions_employee_id_idx ON interactions (employee_id);
CREATE INDEX IF NOT EXISTS invoice_items_product_id_idx ON invoice_items (product_id);
CREATE INDEX IF NOT EXISTS invoice_items_invoice_id_idx ON invoice_items (invoice_id);
CREATE INDEX IF NOT EXISTS invoice_pdf_cache_invoice_id_idx ON invoice_pdf_cache (invoice_id);
CREATE INDEX IF NOT EXISTS invoices_workspace_id_idx ON invoices (workspace_id);
CREATE INDEX IF NOT EXISTS invoices_customer_id_idx ON invoices (customer_id);
CREATE INDEX IF NOT EXISTS invoices_supplier_id_idx ON invoices (supplier_id);
CREATE INDEX IF NOT EXISTS invoices_purchase_order_id_idx ON invoices (purchase_order_id);
CREATE INDEX IF NOT EXISTS journal_lines_account_id_idx ON journal_lines (account_id);
CREATE INDEX IF NOT EXISTS leaves_employee_id_idx ON leaves (employee_id);
CREATE INDEX IF NOT EXISTS ledger_entries_account_id_idx ON ledger_entries (account_id);
CREATE INDEX IF NOT EXISTS notifications_workspace_id_idx ON notifications (workspace_id);
CREATE INDEX IF NOT EXISTS opportunities_customer_id_idx ON opportunities (customer_id);
CREATE INDEX IF NOT EXISTS password_reset_tokens_workspace_id_idx ON password_reset_tokens (workspace_id);
CREATE INDEX IF NOT EXISTS payrolls_employee_id_idx ON payrolls (employee_id);
CREATE INDEX IF NOT EXISTS products_workspace_id_idx ON products (workspace_id);
CREATE INDEX IF NOT EXISTS project_members_employee_id_idx ON project_members (employee_id);
CREATE INDEX IF NOT EXISTS project_members_project_id_idx ON project_members (project_id);
CREATE INDEX IF NOT EXISTS project_tasks_project_id_idx ON project_tasks (project_id);
CREATE INDEX IF NOT EXISTS project_time_entries_employee_id_idx ON project_time_entries (employee_id);
CREATE INDEX IF NOT EXISTS project_time_entries_project_id_idx ON project_time_entries (project_id);
CREATE INDEX IF NOT EXISTS purchase_order_items_product_id_idx ON purchase_order_items (product_id);
CREATE INDEX IF NOT EXISTS purchase_order_items_purchase_order_id_idx ON purchase_order_items (purchase_order_id);
CREATE INDEX IF NOT EXISTS purchase_orders_invoice_id_idx ON purchase_orders (invoice_id);
CREATE INDEX IF NOT EXISTS purchase_orders_supplier_id_idx ON purchase_orders (supplier_id);
CREATE INDEX IF NOT EXISTS stock_movements_product_id_idx ON stock_movements (product_id);
CREATE INDEX IF NOT EXISTS subscriptions_workspace_id_idx ON subscriptions (workspace_id);
CREATE INDEX IF NOT EXISTS transactions_workspace_id_idx ON transactions (workspace_id);
CREATE INDEX IF NOT EXISTS transactions_customer_id_idx ON transactions (customer_id);
CREATE INDEX IF NOT EXISTS transactions_invoice_id_idx ON transactions (invoice_id);
CREATE INDEX IF NOT EXISTS transactions_supplier_id_idx ON transactions (supplier_id);
CREATE INDEX IF NOT EXISTS user_roles_workspace_id_idx ON user_roles (workspace_id);
CREATE INDEX IF NOT EXISTS warehouse_stock_product_id_idx ON warehouse_stock (product_id);
CREATE INDEX IF NOT EXISTS warehouse_stock_warehouse_id_idx ON warehouse_stock (warehouse_id);
CREATE INDEX IF NOT EXISTS work_orders_product_id_idx ON work_orders (product_id);
CREATE INDEX IF NOT EXISTS workflow_instances_workspace_id_idx ON workflow_instances (workspace_id);
CREATE INDEX IF NOT EXISTS workflow_instances_workflow_id_idx ON workflow_instances (workflow_id);
CREATE INDEX IF NOT EXISTS workflow_steps_workflow_id_idx ON workflow_steps (workflow_id);
CREATE INDEX IF NOT EXISTS workflows_workspace_id_idx ON workflows (workspace_id);
CREATE INDEX IF NOT EXISTS workspace_invites_workspace_id_idx ON workspace_invites (workspace_id);
CREATE INDEX IF NOT EXISTS workspace_members_workspace_id_idx ON workspace_members (workspace_id);
CREATE INDEX IF NOT EXISTS invoices_workspace_id_created_at_idx ON invoices (workspace_id, created_at);
CREATE INDEX IF NOT EXISTS invoices_workspace_id_customer_id_idx ON invoices (workspace_id, customer_id);
CREATE INDEX IF NOT EXISTS invoices_workspace_id_status_idx ON invoices (workspace_id, status);
CREATE INDEX IF NOT EXISTS transactions_workspace_id_customer_id_idx ON transactions (workspace_id, customer_id);
CREATE INDEX IF NOT EXISTS transactions_workspace_id_created_at_idx ON transactions (workspace_id, created_at);
CREATE INDEX IF NOT EXISTS customers_workspace_id_full_name_idx ON customers (workspace_id, full_name);
CREATE INDEX IF NOT EXISTS products_workspace_id_name_idx ON products (workspace_id, name);
CREATE INDEX IF NOT EXISTS products_workspace_id_sku_idx ON products (workspace_id, sku);
CREATE INDEX IF NOT EXISTS activities_workspace_id_entity_type_entity_id_idx ON activities (workspace_id, entity_type, entity_id);
CREATE INDEX IF NOT EXISTS workspace_members_user_id_workspace_id_idx ON workspace_members (user_id, workspace_id);

COMMIT;
